

CC:= gcc
AR:= ar

SRC = $(wildcard SRC/*.c)
OBJS = $(SRC:.c=.o)

PROJECTNAME := Utils

SOLOICESKYDIR := 	/cygdrive/d/soloicesky
INCDIR = $(SOLOICESKYDIR)/Includes

#LIBDIR := ./LIB

TARGET = main

all:$(OBJS)
	$(CC) $(OBJS) -o $(TARGET) 
$(OBJS):%.o:%.c
	$(CC) -c $< -o $@ -I$(INCDIR)

########################################################################################
#make lib
########################################################################################

TARGETLIB := libUtils.a

slib:
	 $(AR) -cr $(TARGETLIB) SRC/Utils.o


#copy to the  release directory
RELEASEDIR := $(SOLOICESKYDIR)/$(PROJECTNAME)/realease
	 
release:
	cp -rf $(TARGETLIB) $(RELEASEDIR)/libs/static
	cp -rf SRC/*.h $(RELEASEDIR)/includes
	cp -rf SRC/*.h $(INCDIR)
clean:
	rm $(OBJS) $(TARGET)